let skillsbuild = require("./Images/skillsbuild.png");
let mindspark = require("./Images/mindspark.png");
let developer = require("./Images/developer.png");

// If we are able to map plurals to singular, then update terms to match:

export const courseData = [
    {"id":"001",
    "name":"IBM SkillsBuild",
    "description":"The IBM SkillsBuild page for Artificial Intelligence, containing the courses, software, and resources needed for your learning journey.",
    "duration":-1,
    "image":skillsbuild,
    "prereq":["003"],
    "postreq":["004"],
    "difficulty":1,
    "terms":["IBM","Resources","Software","AI","Basics","Skills"],
    "link":"https://www.ibm.com/academic/topic/artificial-intelligence"},
    
    {"id":"003",
    "name":"Mindspark AI Education",
    "description":"An online professional learning suite of free live and on-demand webinars, crafted by and for educators. Features nine webinars which will guide educators through AI’s foundational concepts.",
    "duration":-1,
    "image":mindspark,
    "prereq":[],
    "postreq":["001","004"],
    "difficulty":1,
    "terms":["Teaching","Education","Students","School","AI","Ethics","Humans","Basics","Inclusivity"],
    "link":"https://www.mindspark.org/ibm-ai"},
    
    {"id":"004",
    "name":"IBM Developer",
    "description":"Learn in-demand skills, build solutions with real sample code, and connect with a global community of developers.",
    "duration":-1,
    "image":developer,
    "prereq":["001","003"],
    "postreq":[],
    "difficulty":3,
    "terms":["Programming","Development","Software","Languages","IBM","Machine Learning","Deep Learning","Application Modernization","Messaging"],
    "link":"https://developer.ibm.com/technologies/artificial-intelligence/"},
    
    {"id":"101",
    "name":"Getting Started with Enterprise-grade AI",
    "description":"This course covers the foundations of Artificial Intelligence for business, including the following topics: AI Evolution, AI Industry Adoption Trends, Natural Language Processing and Virtual Agents.",
    "duration":5,
    "image":skillsbuild,
    "prereq":[],
    "postreq":["102","103","104","105"],
    "difficulty":1,
    "terms":["Industry","AI","Basics","NLP","Evolution","Watson","Chatbot"],
    "link":"https://keyskill-clms.comprehend.ibm.com/course/view.php?id=236"},

    {"id":"102",
    "name":"IBM Watson Machine Learning Essentials",
    "description":"Watson Machine Learning is a service on IBM Cloud with features for training and deploying machine learning models and neural networks. This course consists of a series of videos showing how to use the Watson Machine Learning in Watson Studio.",
    "duration":-1,
    "image":skillsbuild,
    "prereq":["101","403"],
    "postreq":["405","410"],
    "difficulty":2,
    "terms":["Watson","Cloud","Videos","AI","Neural Networks","Machine Learning","Data"],
    "link":"https://learn.ibm.com/course/view.php?id=4482"},
    
    {"id":"103",
    "name":"Data Refinery Essentials",
    "description":"Data Refinery is a self-service data preparation client for data scientists, data engineers, and business analysts. With it, you can quickly transform large amounts of raw data into consumable, quality information that’s ready for analytics.",
    "duration":-1,
    "image":skillsbuild,
    "prereq":["101"],
    "postreq":["409","410","411"],
    "difficulty":2,
    "terms":["Refinery","Data","Raw","CSV","Watson"],
    "link":"https://learn.ibm.com/course/view.php?id=4480"},
    
    {"id":"104",
    "name":"IBM Watson Knowledge Catalog Essentials",
    "description":"IBM Watson Knowledge Catalog is a secure enterprise catalog to index, classify, and govern your data with greater efficiency. Manage your data from every angle giving you a 360-degree view of your data so you can create models, uncover insights, and collaborate more effectively.",
    "duration":-1,
    "image":skillsbuild,
    "prereq":["101"],
    "postreq":["409","410"],
    "difficulty":2,
    "terms":["Watson","Data","Analysis","Assets","Classification","Catalogue","Profiling"],
    "link":"https://learn.ibm.com/course/view.php?id=4481"},
    
    {"id":"105",
    "name":"Watson Academy",
    "description":"A collection of over 100 self-paced online courses teaching you to use Watson AI for a variety of purposes.",
    "duration":-1,
    "image":skillsbuild,
    "prereq":["101","404"],
    "postreq":["405","410"],
    "difficulty":2,
    "terms":["Watson","IBM","Cloud","AI","Basics","Data","Studio","Machine Learning","NLP"],
    "link":"https://www.ibm.com/training/watson"},
    
    {"id":"301",
    "name":"Creating a Spark for Artificial Intelligence",
    "description":"An online introductory webinar designed primarily for teachers. Provides the knowledge and confidence needed to introduce younger students to the basics of AI.",
    "duration":1,
    "image":mindspark,
    "prereq":[],
    "postreq":["302","303","304","402","406"],
    "difficulty":1,
    "terms":["Teaching","AI","Basics","Students","Activities","Play","Inspire","Machine Learning","Neural Networks"],
    "link":"https://www.mindspark.org/ibm-on-demand-webinars/2020/2/7/creating-a-spark-for-artificial-intelligence"},
    
    {"id":"302",
    "name":"AI Here, AI There… AI Who, What, Where?",
    "description":"An online webinar designed primarily for teachers. Provides the knowledge needed to teach students to solve real-world problems using AI.",
    "duration":1,
    "image":mindspark,
    "prereq":["301"],
    "postreq":["405"],
    "difficulty":2,
    "terms":["Teaching","Life","Students","AI","Game","Videos","Activity","Data"],
    "link":"https://www.mindspark.org/ibm-on-demand-webinars/2020/2/7/creating-a-spark-for-artificial-intelligence-4b23m"},
    
    {"id":"303",
    "name":"Ethics in AI - Can You Crack the Moral Code?",
    "description":"An online webinar designed primarily for teachers. Explores the ethical dilemmas through discussions and activities, including words from an IBM AI expert.",
    "duration":1,
    "image":mindspark,
    "prereq":["301"],
    "postreq":["304","412"],
    "difficulty":2,
    "terms":["Ethics","Teaching","Discussion","Students","Activity","AI","Expert"],
    "link":"https://www.mindspark.org/ibm-on-demand-webinars/2020/2/7/creating-a-spark-for-artificial-intelligence-4b23m-5d6tj"},
    
    {"id":"304",
    "name":"AI Can and Should be Inclusive – Design Thinking Can Help!",
    "description":"An online webinar designed primarily for teachers. Grow your understanding of AI through the lens of equity-centered design thinking, then return to the classroom with tools to encourage students to examine and address their own biases.",
    "duration":1,
    "image":mindspark,
    "prereq":["306"],
    "postreq":["412","309"],
    "difficulty":2,
    "terms":["Inclusivity","Equality","Bias","Teaching","AI","Students","Activity"],
    "link":"https://www.mindspark.org/ibm-on-demand-webinars/2020/2/7/creating-a-spark-for-artificial-intelligence-4b23m-5d6tj-je2m6"},
    
    {"id":"305",
    "name":"How Do Siri, Alexa and Watson Understand Me?",
    "description":"An online webinar designed primarily for teachers. Learn to understand the complexities of human language - and what it takes for a computer to understand us! See examples of how NLP can be used for social good, and get students thinking about other applications of this powerful technology.",
    "duration":1,
    "image":mindspark,
    "prereq":["101","301"],
    "postreq":["411"],
    "difficulty":2,
    "terms":["Siri","Alexa","Speech","NLP","Teaching","Students","Life","Social"],
    "link":"https://www.mindspark.org/ibm-on-demand-webinars/2020/2/7/creating-a-spark-for-artificial-intelligence-4b23m-5d6tj-je2m6-t3cj8"},
    
    {"id":"306",
    "name":"Machines Can Learn – But They Need Our Help!",
    "description":"An online webinar designed primarily for teachers. Take part in a larger discussion around intelligence, then learn more specific subsets of machine learning by comparing them to how students learn in the classroom.",
    "duration":1,
    "image":mindspark,
    "prereq":[],
    "postreq":["304","305","308","309"],
    "difficulty":1,
    "terms":["Teaching","Students","AI","Machine Learning","Intelligence","Activity","Thought Experiment"],
    "link":"https://www.mindspark.org/ibm-on-demand-webinars/2020/2/7/creating-a-spark-for-artificial-intelligence-4b23m-5d6tj-je2m6-lw8fp"},
    
    {"id":"307",
    "name":"Amplifying Human Potential - Beyond Programming and Coding",
    "description":"An online webinar designed primarily for teachers. Examines the function of robots in enterprise, what makes a robot artificially intelligent, and how students can be taught to program their own robot",
    "duration":1,
    "image":mindspark,
    "prereq":[],
    "postreq":["302"],
    "difficulty":1,
    "terms":["Robotics","Teaching","Programming","Students","Activity","Life"],
    "link":"https://www.mindspark.org/ibm-on-demand-webinars/2020/2/7/creating-a-spark-for-artificial-intelligence-4b23m-5d6tj-je2m6-t3cj8-l9hs7"},
    
    {"id":"308",
    "name":"AI and Your Curriculum - The Perfect Marriage",
    "description":"An online webinar designed primarily for teachers. Understand the effect AI is having on the future of work, and the skills needed to be successful. Build these employability skills in students to prepare them for anything. Practice these skills with IBM’s “Machine Learning for Kids” Scratch project.",
    "duration":1,
    "image":mindspark,
    "prereq":["301","306"],
    "postreq":["408"],
    "difficulty":2,
    "terms":["Teaching","Classroom","Students","Industry","Scratch","AI","Employability","Skills","Machine Learning"],
    "link":"https://www.mindspark.org/ibm-on-demand-webinars/2020/2/7/creating-a-spark-for-artificial-intelligence-4b23m-5d6tj-je2m6-t3cj8-l9hs7-36c99"},
    
    {"id":"309",
    "name":"Building a Culture of Inclusivity",
    "description":"An online webinar designed primarily for teachers. Examine your own tech experience as you explore the roles of gender, race, and bias in technology and STEM fields. Gain the resources needed to make your students aware of how AI affects them, and join the fight against algorithmic bias and injustice.",
    "duration":1,
    "image":mindspark,
    "prereq":["304"],
    "postreq":["412"],
    "difficulty":2,
    "terms":["Inclusivity","Diversity","Bias","Gender","Race","Teaching","Students","STEM","Algorithm"],
    "link":"https://www.mindspark.org/ibm-on-demand-webinars/2020/2/7/creating-a-spark-for-artificial-intelligence-4b23m-5d6tj-je2m6-t3cj8-l9hs7-36c99-88r6j"},
    
    {"id":"401",
    "name":"Implement trustworthy AI and data governance on AWS using IBM Cloud Pak for Data",
    "description":"Learn step-by-step how to streamline data integration, data governance, analytics, and data virtualization on AWS.",
    "duration":5,
    "image":developer,
    "prereq":["404","103"],
    "postreq":["405"],
    "difficulty":2,
    "terms":["Data","AWS","AI","Amazon","SageMaker","Analysis","Virtualisation","Pandemic","Machine Learning","Bias"],
    "link":"https://developer.ibm.com/learningpaths/pandemic-management-system-aws-ibm-cloud-pak-for-data/"},
    
    {"id":"402",
    "name":"Get started with deep learning",
    "description":"Explore this branch of machine learning that's trained on large amounts of data and deals with computational units working in tandem to perform predictions.",
    "duration":2,
    "image":developer,
    "prereq":["403","101"],
    "postreq":["004","407"],
    "difficulty":2,
    "terms":["Deep learning","Basics","AI","Data","Python","Machine Learning","TensorFlow","Prediction","Architecture"],
    "link":"https://developer.ibm.com/learningpaths/get-started-with-deep-learning/"},
    
    {"id":"403",
    "name":"Get started with machine learning",
    "description":"Designed for anyone interested in quickly getting up to speed with machine learning. Consists of step-by-step tutorials with hands-on demonstrations where you will build models and use them in apps.",
    "duration":2,
    "image":developer,
    "prereq":["003"],
    "postreq":["401","402","407","408","412"],
    "difficulty":1,
    "terms":["Machine Learning","Basics","AI","Python","Scikit","Classification","Regression","Supervised","Unsupervised","Data"],
    "link":"https://developer.ibm.com/learningpaths/learning-path-machine-learning-for-developers/"},
    
    {"id":"404",
    "name":"Get started with artificial intelligence",
    "description":"Learn the basics of artificial intelligence, build and test your first machine learning model using Python and scikit-learn, and try out various artificial intelligence concepts.",
    "duration":2,
    "image":developer,
    "prereq":["003"],
    "postreq":["401","402","414"],
    "difficulty":1,
    "terms":["AI","Basics","Machine Learning","Deep learning", "Neural Networks","NLP","Python","Scikit"],
    "link":"https://developer.ibm.com/learningpaths/get-started-artificial-intelligence/"},
    
    {"id":"405",
    "name":"Find, prepare, and understand data with Watson Knowledge Catalog",
    "description":"Learn how to solve the problems of enterprise data governance using the IBM Watson Knowledge Catalog on IBM Cloud Pak for Data. Use governance, data quality, and active policy management to help you protect and govern sensitive data, trace data lineage, and manage data lakes.",
    "duration":0.75,
    "image":developer,
    "prereq":["401","408"],
    "postreq":[],
    "difficulty":3,
    "terms":["Data","Watson","Categories","Analysis","Policy","Govern","CSV"],
    "link":"https://developer.ibm.com/tutorials/find-prepare-and-understand-data-with-watson-knowledge-catalog/"},
    
    {"id":"406",
    "name":"Build and test your first machine learning model using Python and scikit-learn",
    "description":"In this data science and machine learning tutorial, get a hands-on example on how to create and run a classification model from start to finish. ",
    "duration":0.5,
    "image":developer,
    "prereq":["413","403","404"],
    "postreq":["412","407","409"],
    "difficulty":2,
    "terms":["Machine Learning","Python","Scikit-learn","AI","Data","Classification","Deep learning","Preprocessing","Pipeline"],
    "link":"https://developer.ibm.com/tutorials/build-and-test-your-first-machine-learning-model-using-python-and-scikit-learn/"},
    
    {"id":"407",
    "name":"Use AutoML to find and deploy the best models in minutes",
    "description":"In this learning path, learn how Automated Machine Learning in Watson Studio can prepare data, apply machine learning algorithms, perform hyperparameter optimization, and build model pipelines best suited for your data sets and use cases.",
    "duration":2,
    "image":developer,
    "prereq":["403","404"],
    "postreq":["414"],
    "difficulty":2,
    "terms":["Automatic","Hyperparameter","Watson","Machine Learning","Python","AI","Watson","Data","Pipeline"],
    "link":"https://developer.ibm.com/learningpaths/explore-autoai/"},
    
    {"id":"408",
    "name":"Take control of your data with Watson Studio",
    "description":"Tutorials, articles, and other resources to solve your data science and machine learning needs. IBM Watson Studio simplifies the process of experimentation to deployment, as well as data exploration, model development, and training.",
    "duration":2,
    "image":developer,
    "prereq":["101","403"],
    "postreq":["405","409","410"],
    "difficulty":2,
    "terms":["Watson","IBM","Tutorial","Data","Visualisation","Machine Learning","Deep Learning","Model","Training","Scikit"],
    "link":"https://developer.ibm.com/learningpaths/get-started-watson-studio/"},
    
    {"id":"409",
    "name":"Scrape data from the web using Python and AI",
    "description":"Web scraping involves using a program or algorithm to extract and process large amounts of data from the web. This allows you to find and gather data when there's no direct way to download it.",
    "duration":0.5,
    "image":developer,
    "prereq":["413","408"],
    "postreq":[],
    "difficulty":3,
    "terms":["Scrape","Internet","AI","NLP","Python","Data","Keywords","Refinery"],
    "link":"https://developer.ibm.com/tutorials/scrape-data-from-the-web-using-watson-studio/"},
    
    {"id":"410",
    "name":"Entity extraction using Watson Natural Language Processing",
    "description":"Step through the processing of using Watson NLP to extract entities, keywords, and phrases. These entities can include names of people, organization names, dates, prices, and facilities.",
    "duration":1,
    "image":developer,
    "prereq":["408","305"],
    "postreq":[],
    "difficulty":3,
    "terms":["NLP","Watson","Keywords","Machine Learning","Python","Visualisation"],
    "link":"https://developer.ibm.com/tutorials/entity-extraction-using-watson-nlp/"},
    
    {"id":"411",
    "name":"Convert speech to text, and extract meaningful insights from data",
    "description":"Walk through the steps of preprocessing a speech data set, using the Watson Speech to Text Service to transcribe speech data, and extracting meaningful insights from data with the Watson Natural Language Processing library.",
    "duration":1,
    "image":developer,
    "prereq":["408","305"],
    "postreq":[],
    "difficulty":3,
    "terms":["Speech","NLP","Analysis","Kubernetes","Python"],
    "link":"https://developer.ibm.com/tutorials/extract-meaningful-insights-from-data/"},
    
    {"id":"412",
    "name":"Build fair and robust machine learning models",
    "description":"Explore how Watson Studio uses the AI Fairness 360 Toolkits to test for bias and mitigate bias in data sets and models. Learn how to create a Watson Studio project, set up trusted AI AIF360 Toolkits in the Watson Studio notebook, and run the AIF360 Toolkit on the cloud.",
    "duration":0.5,
    "image":developer,
    "prereq":["304","403"],
    "postreq":["405"],
    "difficulty":2,
    "terms":["Bias","Prejudice","Discrimination","Watson","AI","Machine Learning","Data"],
    "link":"https://developer.ibm.com/tutorials/build-fair-robust-machine-learning-models/"},
    
    {"id":"413",
    "name":"Beginner's guide to Python",
    "description":"We'll introduce the basic concepts you need to know to get started with this straightforward programming language and show you how to use Python for everything from running algebraic calculations to generating graphical output from your data.",
    "duration":0.5,
    "image":developer,
    "prereq":[],
    "postreq":["406"],
    "difficulty":1,
    "terms":["Python","Basics","Coding","Tutorial","Variables","Analytics"],
    "link":"https://developer.ibm.com/articles/os-beginners-guide-python/"},
    
    {"id":"414",
    "name":"Build and train a neural network with nothing but JavaScript",
    "description":"In this tutorial, we will show how it’s possible to build, train, and use a deep neural network (DNN) with nothing but JavaScript. You will learn the base concepts of DNNs, how they work, and how people create and improve them.",
    "duration":0.75,
    "image":developer,
    "prereq":["415"],
    "postreq":["004"],
    "difficulty":3,
    "terms":["Neural Networks","Basics","AI","UI","Javascript","Machine Learning"],
    "link":"https://developer.ibm.com/tutorials/build-a-neural-network-with-nothing-but-javascript-using-brainjs/?mhsrc=ibmsearch_a&mhq=neural%20networks"},
    
    {"id":"415",
    "name":"Get started with Node.js",
    "description":"Node.js is an open source, cross-platform JavaScript runtime environment for developing server-side and networking applications. If you have experience with any programming language, you should be able to follow this course.",
    "duration":2,
    "image":developer,
    "prereq":["413"],
    "postreq":["414"],
    "difficulty":2,
    "terms":["Javascript","Programming","Software"],
    "link":"https://developer.ibm.com/learningpaths/get-started-nodejs/"}
]
;