const globalVariables = {
    "session":"",
    "isLoggedIn":false,
    "currentCourseID":"",
    "transitioning":false,
    "presenting":false,
    "inputProcessing":false,
    "mini":false,
    "home":true,
    "input":"",
    "lastInput":"",
    "currentReply":"",
    "dotting":false,
    "dotDelay":0,
    "results":[],
    "offered":[],
    "journey":"",
    "forceDifficulty":0,
    "journeyList":[null,null,null],
    "eventListened":false,
    "baseTerms":["ai","software","resources","basics","skills","IBM","teaching","education","students","school","ethics","humans","inclusivity","development","machine learning","deep learning","programming","languages","applicaton modernization","messaging","industry","nlp","evolution","watson","chatbot","cloud","neural networks","videos","data","refinery","csv","raw","catalog","analysis","assets","profiling","classification","studio","algorithm","play","activities","inspire","appliation","life","game","discussion","experts","equality","bias","speech","siri","alixa","social","thought experiment","robotics","scratch","skills","stem","diversity","gender","race","aws","amazon","sagemaker","pandemic","virtualisation","prediction","architecture","python","tensorflow","scikit","regression","supervised","unsupervised","visual","policy","govern","categories","preprocessing","pipeline","automatic","hyperparameter","model","training","web","scrape","keywords","visualisation","kubernetes","prejudice","discrimination","coding","variables","tutorial","ui","javascript"],
    "synonyms":[["a.i.","artificial intelligence","ai"],
                ["supervised","unsupervised","learning","ml","machine learning"],
                ["keyword","key word","key term","key words","key terms","keyterms","keywords"],
                ["raw data","raw"],
                ["entity extraction","natural language processing","natural language understanding","nlu","nlp"],
                ["auto","automated","automatic"],
                ["web","internet"],
                ["voices","voice","speech"],
                ["beginner","beginners","foundation","foundations","basic","introduction","basics"],
                ["scikit-learn","scikit learn","scikit"],
                ["apply","job","work","business","jobs","industry"],
                ["scraping","scrape",],
                ["person","human","people","humans"],
                ["catalogue","catalog"],
                ["activity","activities"],
                ["real-life","real life","life"],
                ["morality","ethics"],
                ["equity","equality"],
                ["robots","robot","robotics"],
                ["classrooms","classroom","teaching"],
                ["analyse","analytics","analysis"],
                ["virtual","virtualisation"],
                ["predictions","predict","prediction"],
                ["train","training"],
                ["datasets","dataset","data science","data"],
                ["inclusion","inclusivity"],
                ["tutorials","tutorial"],
                ["visualization","visualisation"],
                ["user interface","interaction","interact","ui"],
                ["js","javascript"],
                ["hyperparameters","hyperparameter"]
            ]
};

export default globalVariables;